#!/usr/bin/env bash
# Backup mysql database

# get mysql server password from database
pwd="$1"

# filename for compressed file
file_name="$(date +"%d-%m-%y").tar.gz"

# Dump sql database
mysqldump -uroot --password="$pwd" --all-databases > backup.sql

# compress database
tar -czf "$file_name" "backup.sql"
