#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes

Hour=0

while ((Hour <= 12))
do
	mins=1
	echo "Hour: $Hour"
	while ((mins < 60))
	do
		echo "$mins"
		((mins++))
	done
	((Hour++))
done
