#!/usr/bin/env bash
# Configure ufw so that it blocks all incoming traffic, except 22, 443, and 80

sudo apt-get -y update
sudo apt-get -y install ufw
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/http
sudo ufw enable
